[package]
name = "img"
version = "0.1.0"
edition = "2022"
description = "Prints out ASCII conversions of supplied images."


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
