[package]
name = "img-to-ascii"
version = "0.1.1"
edition = "2021"
description = "Prints out ASCII conversions of supplied images."
authors = ["Rama Needer <https://github.com/Icey-berg>"]
repository = "https://github.com/Icey-berg/img-to-ascii"
publish = false

[dependencies]
image = "0.24.2"
